### ISSUE TITLE
v0.10.0 image missing on dockerhub

### ISSUE THREAD

**Issue by mxmxchere** [clastix/cluster-api-control-plane-provider-kamaji#114]
The newest tag on dockerhub (that i can see) is v0.9.0. https://github.com/clastix/cluster-api-control-plane-provider-kamaji/blob/0409f977a3a4e608cddbaaa129e266e9725718ad/config/control-plane-components.yaml#L13490 is referring to v0.10.0 which is not on dockerhub (yet).

**Comment by prometherion** [comment]
You're right, [CI](https://github.com/clastix/cluster-api-control-plane-provider-kamaji/actions/runs/9716592995/job/26820484170) didn't complain it didn't work, and it's green 🙃

**Comment by mxmxchere** [comment]
thanks for the quick fix :)
