### ISSUE TITLE
e2e coverage

### ISSUE THREAD

**Issue by prometherion** [clastix/cluster-api-control-plane-provider-kamaji#15]
At the current stage, we're missing any e2e coverage,

Furthermore, we have to run an e2e test for each supported infrastructure provider.

**Comment by dineshba** [comment]
I am interested to contribute to this issue.

Approach for creating E2E in github actions:
```
- create kind cluster
- Install cluster-api
- Install kamaji
- Install PR based cluster-api-control-plane-provider-kamaji
- Install kubevirt provider as infra provider (as kubevirt doesnt require any extra infra or cloud account). Not sure if it will work out of the box in github actions
- Create target cluster with kamaji controlplane and kubevirt infra
- Get the kubeconfig of target cluster and test health of target cluster.
- Install sample pod and if all are working
```
Please let me know if I am in right direction for the e2e tests @prometherion

**Comment by prometherion** [comment]
It could work, thanks @dineshba!

It would be cool having in the long run credits to test over all the infrastructure providers, but this would be a good leap forward on more reliability.

Please, if you have any questions, let's sync on #kamaji Kubernetes Slack workspace channel.
