### ISSUE TITLE
"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: kamaji.clastix.io/v1alpha1: the server could not find the requested resource"

### ISSUE THREAD

**Issue by timstoop** [clastix/cluster-api-control-plane-provider-kamaji#49]
Hi,

I installed version 0.3.0 on our test cluster using the installation method as provides in the release nodes. The `capi-kamaji-controller-manager` is running in the `kamaji-system` namespace, however, it's throwing this error:

```
2023-08-20T11:36:02Z    ERROR   controller-runtime.source.EventHandler  failed to get informer from cache       {"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: kamaji.clastix.io/v1alpha1: the server could not find the requested resource"}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/source/kind.go:68
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/loop.go:62
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
        /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/loop.go:63
k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel
        /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/poll.go:33
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/source/kind.go:56
```

Looks to me like it's missing RBAC permissions?

**Comment by jds9090** [comment]
> Hi,
> 
> I installed version 0.3.0 on our test cluster using the installation method as provides in the release nodes. The `capi-kamaji-controller-manager` is running in the `kamaji-system` namespace, however, it's throwing this error:
> 
> ```
> 2023-08-20T11:36:02Z    ERROR   controller-runtime.source.EventHandler  failed to get informer from cache       {"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: kamaji.clastix.io/v1alpha1: the server could not find the requested resource"}
> sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1
>         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/source/kind.go:68
> k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1
>         /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/loop.go:62
> k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
>         /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/loop.go:63
> k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel
>         /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/poll.go:33
> sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1
>         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/source/kind.go:56
> ```
> 
> Looks to me like it's missing RBAC permissions?

Did you install kamaji controller in your cluster?
(getting started : https://kamaji.clastix.io/getting-started/)

**Comment by timstoop** [comment]
I did not :sweat_smile: 

That said, it's not really mentioned anywhere in this repo that I noticed. I know it kinda makes sense, now that I think about it, but having it in the docs would be nice as well.

**Comment by prometherion** [comment]
@timstoop Unfortunately there's no way to inject dependencies using the `clusterctl` manifests.

Your point in increasing the documentation without giving anything for granted is valid, please, contribute to the project since it's much easier reading a markdown file rather than looking for errors output in the issues section.
