### ISSUE TITLE
Supporting Tinkerbell CAPI clusters

### ISSUE THREAD

**Issue by prometherion** [clastix/cluster-api-control-plane-provider-kamaji#8]
We're actively looking for a development environment based on Tinkerbell (aka Equinix) to test it.

**Comment by EntraptaJ** [comment]
I’m looking at adopting this project shortly, I use Tinkerbell within my infrastructure and am happy to see what I can do to get this supported!

**Comment by prometherion** [comment]
@EntraptaJ thanks for sharing this!

Usually, we work back to back with the adopter which offers its environment to develop the integration. Since the environment could host sensitive data, I would suggest getting in touch privately with me on LinkedIn, Twitter, or via CLASTIX's website contact page to keep the confidentiality of the Control Plane endpoint and any other sensitive data.

Looking forward to working together for this integration! 🙌🏻

**Comment by EntraptaJ** [comment]
Sorry about the long delay, needed to build up some other things before I got everything in place for messing with the new bare metal provisioning system/where I’m actually using Tinkerbell, I should be able to start focusing on this in the next week or two. And I actually got Eclipse Che working in my cluster to replace GitPods so I have a good dev environment to work on (I do everything from my iPad lol)

**Comment by chrisdoherty4** [comment]
Hi folks. Tinkerbell maintainer here. If there's anything we can do to assist don't hesitate to reach out! Happy to help on the Kamaji side also.

**Comment by prometherion** [comment]
Thanks for jumping in, @chrisdoherty4!

Essentially, Kamaji provides Control Plane as a Service, and our implementation patches the Infrastructure Cluster with the provided endpoint which the Kubernetes API Server is ready to serve traffic.

I was taking a look at the Tinkerbell CAPI code: https://github.com/tinkerbell/cluster-api-provider-tinkerbell/blob/22b268b1b3d2cfb43ff5286efa47080fada59209/controllers/tinkerbellcluster_controller.go#L193-L203

The following steps should work, especially:
1. the cluster administrator applies all the CAPI manifests
2. the Tinkerbell Infrastructure Cluster reconciliation fails since Kamaji hasn't yet created a LB
3. Kamaji creates the LB and populates the Tinkerbell Infrastructure Cluster's `controlPlaneEnpoint` spec key
4. the Tinkerbell Infrastructure Cluster succeed
5. all the CAPI magic

Considering also the CAPI state machine in regard of the [Cluster resource](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster), I think we just need to support the patch for the `TinkerbellCluster` resource and we can mark it as "supported".

**Comment by chrisdoherty4** [comment]
That sounds like it'll work. Do you need help testing?

**Comment by prometherion** [comment]
Sorry @chrisdoherty4, I had so many things at the same time and I didn't reply.

The plan is to release support for Tinkerbell clusters, since _it should work_ (famous last words ™️).

I'll add this to the v0.8.0 release so the community can give it a spin, in case of errors we can fix those.
