### ISSUE TITLE
kubeconfig secret is created with the wrong type

### ISSUE THREAD

**Issue by hexchen** [clastix/cluster-api-control-plane-provider-kamaji#92]
By convention it should be of the type `cluster.x-k8s.io/secret` instead of `Opaque` when getting copied from the TenantControlPlane-managed secret.

**Comment by prometherion** [comment]
Thanks for opening this, @hexchen!

May I ask you what's the impact level of this bug? So far I'm running Kamaji on CAPI v1.5 with no issues, even tho the type is potentially wrong.

**Comment by hexchen** [comment]
Some external operators (the one I am having problems with is https://github.com/dntosas/capi2argo-cluster-operator) expect that type to determine that it is in fact a valid cluster-api kubeconfig. In this case, this leads to the operator not copying the kubeconfig into an argocd secret.

For reference, this is how the kubeadm control plane provider generates this secret: https://github.com/kubernetes-sigs/cluster-api/blob/main/util/kubeconfig/kubeconfig.go#L133

**Comment by prometherion** [comment]
I don't see any problem in changing the Secret type, that would work for new clusters, not sure if type can be changed for already created resources.

If you're open to implement the change, happy to receive more contributions of yours 🎉 

The plan is to release this for v0.8.0
